POST http://127.0.0.1:8080/invoice HTTP/1.1
Content-Type: application/json

# {
#   "type": "sale",
#   "date": "2022-11-17",
#   "itens": [
#     {
#       "quantity": 5,
#       "unitPrice": 165,
#       "product": {
#         "id": 5
#       }
#     },
#     {
#       "quantity": 5,
#       "unitPrice": 330,
#       "product": {
#         "id": 6
#       }
#     }
#   ]
# }
